version: '3'

services:
  # postgres 11 postgis 2.5 -> https://hub.docker.com/r/camptocamp/postgres/tags
  db:
    image: camptocamp/postgres:11-postgis-2.5
    environment:
      POSTGRES_USER: www-data
      POSTGRES_PASSWORD: www-data
      POSTGRES_DB: test_DB
    volumes:
    - ./data/01_init_script.sql:/docker-entrypoint-initdb.d/01_init_script.sql
    ports:
      - 25432:5432

  data:
    image: camptocamp/oereb_fed_data
    build:
      context: .
    environment:
      - ePGHOST=${PGHOST}
      - ePGPORT=${PGPORT}
      - ePGUSER=${PGUSER}
      - ePGPASSWORD=${PGPASSWORD}
      - ePGNAME=${PGDATABASE}
    depends_on:
    - db
    # volumes:
    # - ./scripts:/scripts
